repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.14.4
    values:
      - values/cert-manager.yaml
    set:
      - name: installCRDs
        value: true

  - name: prometheus
    namespace: o11y
    createNamespace: true
    chart: prometheus-community/prometheus
    version: 25.21.0
    values:
      - values/prometheus.yaml

  - name: grafana
    namespace: o11y
    chart: grafana/grafana
    version: 7.3.9
    values:
      - values/grafana.yaml
      - secrets/grafana.enc.yaml