name: Run Tests

on:
  push:
    branches: [ main ]

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.MY_SECRET }}
      DB_USER: ${{ DB_USER }}
      DB_PASS: ${{ DB_PASS }}
      DB_NAME: ${{ DB_NAME }}
      DB_PORT: ${{ DB_PORT }}
      SERVICE_PORT: ${{ SERVICE_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make test
        run: make test
