name: Run Tests

on:
  push:
    branches: [ main ]

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      SERVICE_PORT: ${{ secrets.SERVICE_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make test
        run: make test
