global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'level-scale-app'
    static_configs:
      - targets: ['app:9091']

  - job_name: 'nginx'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginx-exporter:9113']
